"""
Django settings for django_app project.

Generated by 'django-admin startproject' using Django 3.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'z*6x7r&)$t$gw$fedm%2hh!%cxy-r9wrz!6_k72#e*38(l(o!0'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'habits_trainer.apps.HabitsTrainerConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'habits_trainer.timezonemiddleware.TimezoneMiddleware'
]

ROOT_URLCONF = 'django_app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'django_app.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#     }
# }

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'postgres',
#         'USER': 'postgres',
#         'PASSWORD': 'MeD3ydbDj8p66dwe',
#         'HOST': '34.107.77.26',
#         'PORT': '5432',
#         # 'OPTIONS': {
#         #     'sslmode': 'verify-ca',  # leave this line intact
#         #     'sslrootcert': '/your/path/to/server-ca.pem',
#         #     "sslcert": "/your/path/to/client-cert.pem",
#         #     "sslkey": "/your/path/to/client-key.pem",
#         # }
#     }
# }

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'postgres',
#         'USER': 'postgres',
#         'PASSWORD': 'Je4fomzxBP57M0fv',
#         'HOST': '35.246.168.194',
#         'PORT': '3306',
#         # 'OPTIONS': {
#         #     'sslmode': 'verify-ca',  # leave this line intact
#         #     'sslrootcert': '/your/path/to/server-ca.pem',
#         #     "sslcert": "/your/path/to/client-cert.pem",
#         #     "sslkey": "/your/path/to/client-key.pem",
#         # }
#     }
# }

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'habits_tracker',
#         'USER': 'lucas',
#         'PASSWORD': 'system',
#         #'HOST': '35.246.246.174',
#         #'PORT': '3306',
#         'ENGINE': 'django.db.backends.mysql',
#         'HOST': '/cloudsql/habit-trainer-316412:europe-west3:db-habits-trainer-mysql',
#             #'NAME': 'polls',
#             #'USER': '<your-database-user>',
#             #'PASSWORD': '<your-database-password>',
#         # 'OPTIONS': {
#         #     'sslmode': 'verify-ca',  # leave this line intact
#         #     'sslrootcert': '/your/path/to/server-ca.pem',
#         #     "sslcert": "/your/path/to/client-cert.pem",
#         #     "sslkey": "/your/path/to/client-key.pem",
#         # }
#     }
# }

# [START db_setup]
if os.getenv('GAE_APPLICATION', None):
    # Running on production App Engine, so connect to Google Cloud SQL using
    # the unix socket at /cloudsql/<your-cloudsql-connection string>
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'HOST': '/cloudsql/habit-trainer-316412:europe-west3:db-habits-trainer-mysql',
            'USER': 'lucas',
            'PASSWORD': 'system',
            'NAME': 'habits_tracker',
        }
    }
else:
    # Running locally so connect to either a local MySQL instance or connect
    # to Cloud SQL via the proxy.  To start the proxy via command line:
    #    $ cloud_sql_proxy -instances=[INSTANCE_CONNECTION_NAME]=tcp:3306
    # See https://cloud.google.com/sql/docs/mysql-connect-proxy
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'HOST': '127.0.0.1',
            'PORT': '3306',
            'NAME': 'habits_tracker',
            'USER': 'lucas',
            'PASSWORD': 'system',
        }
    }
# [END db_setup]


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

# STATIC_URL = '/static/'
ALLOWED_HOSTS = ['*']
# X_FRAME_OPTIONS = '*'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/
# Google App Engine: set static root for local static files
# https://cloud.google.com/appengine/docs/flexible/python/serving-static-files
STATIC_URL = '/static/'
STATIC_ROOT = 'static'
