# Generated by Django 3.0.12 on 2021-07-05 14:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('habits_trainer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='acceptance',
            field=models.FloatField(default=1, null=True),
        ),
    ]
