# Generated by Django 3.0.12 on 2021-07-05 15:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('habits_trainer', '0002_task_acceptance'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='tenthLastDoneDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
