# Generated by Django 3.0.12 on 2021-07-26 18:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('habits_trainer', '0004_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='vapid',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
