# Generated by Django 3.1.6 on 2021-02-08 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits_trainer', '0004_auto_20210208_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='intitalInterval',
            field=models.FloatField(default=7.0),
        ),
        migrations.AlterField(
            model_name='taskcompleted',
            name='doneDate',
            field=models.DateTimeField(blank=True),
        ),
    ]
