# Generated by Django 3.1.6 on 2021-02-08 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits_trainer', '0005_auto_20210208_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcompleted',
            name='doneDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
