# Generated by Django 3.0.12 on 2021-07-27 12:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('habits_trainer', '0005_auto_20210726_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='vapid',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
