# Generated by Django 3.1.6 on 2021-02-12 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits_trainer', '0006_auto_20210208_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskcompleted',
            name='behavior',
        ),
        migrations.RemoveField(
            model_name='taskcompleted',
            name='doneDate',
        ),
    ]
