# Generated by Django 3.1.6 on 2021-02-12 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits_trainer', '0007_auto_20210212_1539'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaskCompleted',
            new_name='TaskFeedback',
        ),
    ]
