# Generated by Django 3.0.12 on 2021-07-27 14:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('habits_trainer', '0008_auto_20210727_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='notified',
            field=models.BooleanField(default=False),
        ),
    ]
