# Generated by Django 3.1.6 on 2021-02-12 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('habits_trainer', '0008_auto_20210212_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskDone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doneDate', models.DateTimeField(blank=True, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habits_trainer.task')),
            ],
        ),
    ]
