# Generated by Django 3.1.6 on 2021-02-12 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits_trainer', '0009_taskdone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskdone',
            name='doneDate',
            field=models.DateTimeField(null=True),
        ),
    ]
