# Generated by Django 3.0.12 on 2021-08-04 10:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('habits_trainer', '0009_task_notified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='vapid',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
