# Generated by Django 3.1.6 on 2021-02-12 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits_trainer', '0010_auto_20210212_1708'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='intitalInterval',
            new_name='initialInterval',
        ),
    ]
