# Generated by Django 3.0.12 on 2021-08-09 14:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('habits_trainer', '0010_auto_20210804_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='clientID',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
