# Generated by Django 3.1.6 on 2021-02-15 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits_trainer', '0011_auto_20210212_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskfeedback',
            name='feedback',
            field=models.CharField(choices=[('DONE', 'Done'), ('LATER', 'Later')], default='DONE', max_length=10),
        ),
    ]
