# Generated by Django 3.0.12 on 2021-08-11 15:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('habits_trainer', '0012_remove_profile_clientid'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='notified',
            field=models.BooleanField(default=False),
        ),
    ]
