# Generated by Django 3.1.6 on 2021-02-15 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits_trainer', '0012_taskfeedback_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskdone',
            name='predicted_next_date',
            field=models.DateTimeField(null=True),
        ),
    ]
