# Generated by Django 3.1.6 on 2021-02-15 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits_trainer', '0013_taskdone_predicted_next_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskdone',
            name='predicted_next_date',
        ),
    ]
