# Generated by Django 3.1.6 on 2021-02-15 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits_trainer', '0014_remove_taskdone_predicted_next_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='initialInterval',
            new_name='targetInterval',
        ),
    ]
