# Generated by Django 3.0.12 on 2021-02-18 10:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('habits_trainer', '0015_auto_20210215_1537'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskdone',
            old_name='doneDate',
            new_name='done_date',
        ),
    ]
